version: "3.3"

services:
  dojopuzzles-app:
    build: .
    container_name: dojopuzzles-app
    restart: always
    volumes:
      - dojopuzzles_static_data:/dojopuzzles/static
    expose:
      - "8100"
    ports:
      - "8100:80"
    env_file:
      - .dojopuzzles-app.env
    command: "/dojopuzzles/start_app.sh"
    networks:
      - nginx-proxy

  dojopuzzles-app-static:
    image: nginx:latest
    container_name: dojopuzzles-app-static
    restart: always
    volumes:
      - dojopuzzles_static_data:/usr/share/nginx/html
    env_file:
      - .dojopuzzles-app-static.env
    depends_on:
      - dojopuzzles-app
    expose:
      - "80"
    networks:
      - nginx-proxy

volumes:
  dojopuzzles_static_data:

networks:
  nginx-proxy:
    external: true
